# ---------------- #
#   Main Configs   #
# ---------------- #
# Short bio or description (displayed in the header)
description: Programmer From Somewhere On Earth
baseurl: "/binzblog"
url:
date_format: "ordinal"
title: BINGO
subtitle: "知行合一"
description: "Binz的个人博客"
keywords: BINGO, binz, 知行合一, BinBin
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Bin Zhe
organization: binzhome.com
organization_url: http://www.binzhome.com
github_username: binz123
location: Zhuhai, China
email: bzkmjc123@163.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页
    icon: octicon-home

  -
    href: /categories/
    label: 分类
    icon: octicon-book

  -
    href: /wiki/
    label: 维基
    icon: octicon-mortar-board

  -
    href: /links/
    label: 链接
    icon: octicon-globe
  -
    href: /about/
    label: 关于
    icon: octicon-gist-secret

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: binz123/binzblog.github.io
# Support for LiveRe comments system.
# You can get your uid from https://livere.com/insight/myCode (General web site)
gitment:
    username: binz123
    repo: binzblog-comments
    oauth:
      user_id: ba21e206004219760e3f
      user_sercret: 3aca8eb8f2cae89cec10f1cef181203ae6893721
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : true
# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
